# Generated by Django 3.0.7 on 2020-06-08 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30)),
                ('new', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='productimage')),
            ],
        ),
        migrations.CreateModel(
            name='TodaySales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_today', models.FloatField()),
                ('sales_same_day_last_year', models.FloatField()),
                ('monthly_increase_on_sales', models.FloatField()),
                ('sold_qty', models.IntegerField(default=0)),
                ('ad_cost', models.FloatField()),
                ('acos', models.FloatField()),
                ('ad_cost_on_sales', models.FloatField()),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TodayProductSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_qty', models.IntegerField(default=0)),
                ('sales_amount', models.FloatField()),
                ('sold_qty_average_7d', models.FloatField()),
                ('average_price_7d', models.FloatField()),
                ('inventory', models.IntegerField(default=0)),
                ('lasting_day_estimated_by_amazon', models.IntegerField(default=0)),
                ('lasting_day_estimated_by_us', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesMonitor.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Last7dayProductSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_qty', models.IntegerField(default=0)),
                ('sales_amount', models.FloatField()),
                ('sold_qty_average_7d', models.FloatField()),
                ('average_price_7d', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesMonitor.Product')),
            ],
        ),
    ]
