# Generated by Django 3.0.7 on 2020-06-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0002_auto_20200608_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesLastYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1)),
                ('month', models.IntegerField(default=1)),
                ('sales', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='todaysales',
            name='sold_qty',
        ),
        migrations.AddField(
            model_name='todaysales',
            name='sales_month_to_date',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='todaysales',
            name='monthly_increase_on_sales',
            field=models.FloatField(default=0),
        ),
    ]
