# Generated by Django 3.0.7 on 2020-06-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0003_auto_20200608_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbaInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('asin', models.CharField(max_length=30)),
                ('total_unit', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('inbound_fc_unit', models.IntegerField(default=0)),
                ('days_of_supply', models.IntegerField(default=0)),
                ('recommended_replenishment_qty', models.IntegerField(default=0)),
                ('recommended_ship_date', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
