# Generated by Django 3.0.7 on 2020-06-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0005_fbainventory_fnsku'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShenzhenInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('qty', models.IntegerField(default=0)),
            ],
        ),
    ]
