# Generated by Django 3.0.7 on 2020-06-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0006_shenzheninventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivablePurchasedQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('qty', models.IntegerField(default=0)),
            ],
        ),
    ]
