# Generated by Django 3.0.7 on 2020-06-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0007_receivablepurchasedqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayproductsales',
            name='average_price_7d',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='todayproductsales',
            name='lasting_day_estimated_by_us',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='todayproductsales',
            name='sales_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='todayproductsales',
            name='sold_qty_average_7d',
            field=models.FloatField(default=0),
        ),
    ]
