# Generated by Django 3.0.7 on 2020-06-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0008_auto_20200609_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todayproductsales',
            name='inventory',
        ),
        migrations.AddField(
            model_name='todayproductsales',
            name='fba_inventory',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='salesMonitor.FbaInventory'),
            preserve_default=1,
        ),
    ]
