# Generated by Django 3.0.7 on 2020-06-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0009_auto_20200620_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbainventory',
            name='fc_unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fbainventory',
            name='inbound_unit',
            field=models.IntegerField(default=0),
        ),
    ]
