# Generated by Django 3.0.7 on 2020-06-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0010_auto_20200620_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='todayproductsales',
            name='lasting_day_of_available_estimated_by_us',
            field=models.FloatField(default=0),
        ),
    ]
