# Generated by Django 3.0.7 on 2020-07-05 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0013_todayproductsales_lasting_day_of_total_fba_unit_estimated_by_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTodayProductSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sold_qty', models.IntegerField(default=0)),
                ('sales_amount', models.FloatField(default=0)),
                ('sold_qty_average_7d', models.FloatField(default=0)),
                ('average_price_7d', models.FloatField(default=0)),
                ('lasting_day_estimated_by_amazon', models.IntegerField(default=0)),
                ('lasting_day_estimated_by_us', models.FloatField(default=0)),
                ('lasting_day_of_available_estimated_by_us', models.FloatField(default=0)),
                ('lasting_day_of_available_fc_estimated_by_us', models.FloatField(default=0)),
                ('lasting_day_of_total_fba_unit_estimated_by_us', models.FloatField(default=0)),
                ('fba_inventory', models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='salesMonitor.FbaInventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesMonitor.Product')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryLast7dayProductSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sold_qty', models.IntegerField(default=0)),
                ('sales_amount', models.FloatField()),
                ('sold_qty_average_7d', models.FloatField()),
                ('average_price_7d', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesMonitor.Product')),
            ],
        ),
    ]
