# Generated by Django 3.0.7 on 2020-07-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0014_historylast7dayproductsales_historytodayproductsales'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTodaySales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sales_today', models.FloatField()),
                ('sales_same_day_last_year', models.FloatField()),
                ('sales_month_to_date', models.FloatField(default=0)),
                ('monthly_increase_on_sales', models.FloatField(default=0)),
                ('ad_cost', models.FloatField()),
                ('acos', models.FloatField()),
                ('ad_cost_on_sales', models.FloatField()),
            ],
        ),
    ]
