# Generated by Django 3.0.7 on 2020-07-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0015_historytodaysales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodaySales',
        ),
    ]
