# Generated by Django 3.0.7 on 2020-07-16 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0016_delete_todaysales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=15, unique=True)),
                ('sku', models.CharField(default='', max_length=30)),
                ('qty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShippedSkuQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=30)),
                ('qty', models.IntegerField(default=0)),
                ('shipped_date', models.DateField()),
                ('estimated_receiving_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salesMonitor.Product')),
            ],
        ),
        migrations.CreateModel(
            name='FbaShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=15, unique=True)),
                ('shipment_name', models.CharField(max_length=50, unique=True)),
                ('shipped_sku_qties', models.ManyToManyField(to='salesMonitor.ShippedSkuQty')),
            ],
        ),
    ]
