# Generated by Django 3.0.7 on 2020-07-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0017_fbashipment_inventory_shippedskuqty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShenzhenInventory',
        ),
    ]
