# Generated by Django 3.0.7 on 2020-07-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0018_delete_shenzheninventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='warehouse_name',
            field=models.CharField(max_length=15),
        ),
    ]
