# Generated by Django 3.0.7 on 2020-07-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0019_auto_20200716_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todayproductsales',
            name='lasting_day_estimated_by_amazon',
        ),
        migrations.AddField(
            model_name='product',
            name='discontinued',
            field=models.BooleanField(default=False),
        ),
    ]
