# Generated by Django 3.0.7 on 2020-07-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0020_auto_20200716_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historytodayproductsales',
            name='lasting_day_estimated_by_amazon',
        ),
    ]
