# Generated by Django 3.0.7 on 2020-07-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0021_remove_historytodayproductsales_lasting_day_estimated_by_amazon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippedskuqty',
            name='estimated_receiving_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='shippedskuqty',
            name='shipped_date',
            field=models.DateField(null=True),
        ),
    ]
