# Generated by Django 3.0.7 on 2020-07-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0022_auto_20200717_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedSkuQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=15)),
                ('sku', models.CharField(default='', max_length=30)),
                ('qty', models.IntegerField(default=0)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
    ]
