# Generated by Django 3.0.7 on 2020-07-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0023_receivedskuqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbashipment',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
