# Generated by Django 3.0.7 on 2020-07-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0025_auto_20200717_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedskuqty',
            name='closed',
        ),
    ]
