# Generated by Django 3.0.7 on 2020-07-27 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0026_remove_receivedskuqty_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(default='', max_length=30, unique=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SkuUpc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=30)),
                ('upc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salesMonitor.Upc')),
            ],
        ),
    ]
