# Generated by Django 3.0.7 on 2020-07-27 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0027_skuupc_upc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skuupc',
            name='upc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='salesMonitor.Upc'),
        ),
    ]
