# Generated by Django 3.0.7 on 2021-01-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0031_usersupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersupplier',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='salesMonitor.Supplier'),
        ),
    ]
