# Generated by Django 3.0.7 on 2021-04-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0032_usersupplier_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuPurchasingPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=30)),
                ('purchasing_price', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
