# Generated by Django 3.0.7 on 2021-04-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0033_skupurchasingprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuHeadShippingUnitCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=30)),
                ('type', models.CharField(choices=[('S', 'Sea'), ('A', 'Air'), ('G', 'General')], max_length=1)),
                ('country', models.CharField(max_length=2)),
                ('head_shipping_unit_cost', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
