# Generated by Django 3.0.7 on 2021-04-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0034_skuheadshippingunitcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuAssetLiabilityTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=30)),
                ('sales_person', models.CharField(default='', max_length=30)),
                ('liabilities', models.FloatField(default=0.0)),
                ('date', models.DateField()),
                ('initial_inventory_quantity', models.IntegerField(default=0)),
                ('unit_purchasing_price', models.FloatField(default=0.0)),
                ('initial_inventory_value', models.FloatField(default=0.0)),
                ('head_shipping_unit_price', models.FloatField(default=0.0)),
                ('initial_other_cost', models.FloatField(default=0.0)),
                ('initial_liabilities', models.FloatField(default=0.0)),
                ('initial', models.BooleanField(default=False)),
                ('initial_investment', models.FloatField(default=0.0)),
                ('history_inventment', models.FloatField(default=0.0)),
                ('cash_amount', models.FloatField(default=0.0)),
                ('net_asset_amount', models.FloatField(default=0.0)),
                ('previous_asset_liability_table_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SkuManagedBySalesPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=30)),
                ('sales_person', models.CharField(default='', max_length=30)),
                ('bonus_percent', models.FloatField(default=0.05)),
            ],
        ),
    ]
