# Generated by Django 3.0.7 on 2021-04-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0035_skuassetliabilitytable_skumanagedbysalesperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=30)),
                ('heavy_or_light', models.BooleanField(default=False)),
                ('real_weight', models.FloatField(default=0.25)),
                ('converted_weight', models.FloatField(default=0.3)),
            ],
        ),
    ]
