# Generated by Django 3.0.7 on 2021-04-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0036_skuweight'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbaShipmentCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=15, unique=True)),
                ('shipway', models.CharField(choices=[('S', '海派'), ('A', '空派'), ('E', '快递')], max_length=1)),
                ('cost_per_kg', models.FloatField(default=45.0)),
            ],
        ),
    ]
