# Generated by Django 3.0.7 on 2021-04-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0037_fbashipmentcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbashipmentcost',
            name='shipment_id',
            field=models.CharField(max_length=15),
        ),
    ]
