# Generated by Django 3.0.7 on 2021-04-07 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0038_auto_20210407_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbashipmentcost',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
