# Generated by Django 3.0.7 on 2021-04-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0039_fbashipmentcost_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuPurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=30)),
                ('po_number', models.CharField(default='', max_length=30)),
                ('qty', models.IntegerField(default=0)),
                ('transaction_amount', models.FloatField(default=0.0)),
                ('date', models.DateField()),
            ],
        ),
    ]
