# Generated by Django 3.0.7 on 2021-04-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0040_skupurchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitLossTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=30)),
                ('status', models.CharField(choices=[('T', '交易订单录入'), ('P', '购货和头程运费确认'), ('F', '各种费用扣除'), ('S', '股东分红扣除')], max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sales_amount', models.FloatField(default=0.0)),
                ('sales_quantity', models.IntegerField(default=0)),
                ('product_purchasing_fee', models.FloatField(default=0.0)),
                ('head_shipping_fee', models.FloatField(default=0.0)),
                ('amazon_fee', models.FloatField(default=0.0)),
                ('ad_fee', models.FloatField(default=0.0)),
                ('sales_person', models.CharField(default='lijunjie', max_length=30)),
                ('sales_person_bonus_fee', models.FloatField(default=0.0)),
                ('sales_person_bonus_fee_percent', models.FloatField(default=0.05)),
                ('product_originator_bonus_fee', models.FloatField(default=0.0)),
                ('product_originator_bonus_fee_percent', models.FloatField(default=0.05)),
                ('product_designer_bonus_fee', models.FloatField(default=0.0)),
                ('product_designer_bonus_fee_percent', models.FloatField(default=0.05)),
                ('platform_fee', models.FloatField(default=0.0)),
                ('platform_fee_percent', models.FloatField(default=0.05)),
                ('other_fee', models.FloatField(default=0.0)),
                ('shareholder_bonus_fee', models.FloatField(default=0.0)),
                ('profit_before_deduct_bonus', models.FloatField(default=0.0)),
                ('profit_after_deduct_bounus', models.FloatField(default=0.0)),
            ],
        ),
    ]
