# Generated by Django 3.0.7 on 2021-04-09 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0041_profitlosstable'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitlosstable',
            name='country',
            field=models.CharField(choices=[('US', 'US'), ('CA', 'CA'), ('AU', 'AU'), ('AE', 'AE'), ('UK', 'UK'), ('DE', 'DE'), ('FR', 'FR'), ('IT', 'IT'), ('ES', 'ES'), ('SG', 'SG')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profitlosstable',
            name='currency_rate',
            field=models.FloatField(default=6.5),
        ),
    ]
