# Generated by Django 3.0.7 on 2021-04-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0042_auto_20210409_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=30)),
                ('proposer_name', models.CharField(default='lijunjie', max_length=30)),
                ('designer_name', models.CharField(default='lijunjie', max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='skumanagedbysalesperson',
            old_name='sales_person',
            new_name='sales_person_name',
        ),
        migrations.RemoveField(
            model_name='skuassetliabilitytable',
            name='sales_person',
        ),
        migrations.RemoveField(
            model_name='skumanagedbysalesperson',
            name='bonus_percent',
        ),
        migrations.AddField(
            model_name='skuassetliabilitytable',
            name='for_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skumanagedbysalesperson',
            name='sales_assistant_name',
            field=models.CharField(default='lijunjie', max_length=30),
        ),
    ]
