# Generated by Django 3.0.7 on 2021-10-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0043_auto_20210414_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbainventory',
            name='country',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='historylast7dayproductsales',
            name='country',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='historytodayproductsales',
            name='country',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='historytodaysales',
            name='country',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='last7dayproductsales',
            name='country',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='todayproductsales',
            name='country',
            field=models.CharField(default='US', max_length=2),
        ),
    ]
