# Generated by Django 3.0.7 on 2021-10-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0044_auto_20211008_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbainventory',
            name='fnsku',
            field=models.CharField(default='nofnsku', max_length=30),
        ),
        migrations.AlterField(
            model_name='fbainventory',
            name='sku',
            field=models.CharField(max_length=30),
        ),
    ]
