# Generated by Django 3.0.7 on 2021-10-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0045_auto_20211008_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_country', models.CharField(max_length=2)),
                ('to_country', models.CharField(max_length=2)),
                ('rate', models.FloatField(default=0)),
            ],
        ),
    ]
