# Generated by Django 3.0.7 on 2021-10-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0046_currencyrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skusupplier',
            name='supplier',
        ),
        migrations.AddField(
            model_name='skusupplier',
            name='supplier_id',
            field=models.CharField(default='GYS001', max_length=60),
        ),
    ]
