# Generated by Django 3.0.7 on 2021-10-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0047_auto_20211008_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersupplier',
            name='supplier',
        ),
        migrations.AddField(
            model_name='usersupplier',
            name='supplier_id',
            field=models.CharField(default='GYS001', max_length=60),
        ),
    ]
