# Generated by Django 3.0.7 on 2022-06-20 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0048_auto_20211008_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
