# Generated by Django 3.0.7 on 2022-09-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0049_currencyrate_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentCenterCodeCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('country', models.CharField(default='US', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='fbashipment',
            name='country',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='fbashipment',
            name='fc_code',
            field=models.CharField(default='', max_length=15),
        ),
    ]
