# Generated by Django 3.0.7 on 2022-09-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0050_auto_20220918_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteFulfillmentSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30)),
                ('country', models.CharField(default='CA', max_length=2)),
            ],
        ),
    ]
