# Generated by Django 3.0.7 on 2023-03-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0052_auto_20230130_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbaShipmentPaidBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=15, unique=True)),
                ('paid_amount', models.FloatField(default=0)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
    ]
