# Generated by Django 3.0.7 on 2023-03-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0054_fbashipmentpaidbill_weight_volumn_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventoryUnitValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=30)),
                ('inventory_value', models.FloatField(default=0)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
