# Generated by Django 3.0.7 on 2023-03-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0056_productinventoryunitadditionalvalue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInventoryUnitAdditionalValue',
        ),
        migrations.AddField(
            model_name='productinventoryunitvalue',
            name='additional_cost',
            field=models.FloatField(default=0),
        ),
    ]
