# Generated by Django 3.0.7 on 2023-06-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0057_auto_20230313_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlanProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_plan_number', models.CharField(default='', max_length=30, unique=True)),
                ('qty', models.IntegerField(default=0)),
                ('deadline_date', models.DateField()),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
    ]
