# Generated by Django 3.0.7 on 2023-06-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0059_productionplanprogress_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionplanprogress',
            name='closed',
        ),
        migrations.AddField(
            model_name='productionplanprogress',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
