# Generated by Django 3.0.7 on 2023-06-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0060_auto_20230627_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplanprogress',
            name='manufacturer_number',
            field=models.CharField(default='', max_length=40),
        ),
    ]
