# Generated by Django 3.0.7 on 2023-06-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0061_productionplanprogress_manufacturer_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('production_stage_type_name', models.CharField(default='', max_length=30)),
                ('duration_days', models.IntegerField(default=0)),
                ('start_date_estimated', models.DateField(null=True)),
                ('start_date_actually', models.DateField(null=True)),
                ('order_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionStageTypeParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('production_stages', models.ManyToManyField(to='salesMonitor.ProductionStage')),
            ],
        ),
    ]
