# Generated by Django 3.0.7 on 2023-06-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0062_productionstage_productionstagetypeparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplanprogress',
            name='current_stage_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionplanprogress',
            name='production_stages',
            field=models.ManyToManyField(to='salesMonitor.ProductionStage'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='start_date_actually',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='start_date_estimated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
