# Generated by Django 3.0.7 on 2023-07-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0065_productionplanprogress_current_stage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstage',
            name='daily_production_units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
