# Generated by Django 3.0.7 on 2023-07-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0066_productionstage_daily_production_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skuproductionstagetypeparameter',
            old_name='name',
            new_name='production_type',
        ),
        migrations.AddField(
            model_name='skuproductionstagetypeparameter',
            name='production_type_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
