# Generated by Django 3.0.7 on 2023-07-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0067_auto_20230703_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skuproductionstagetypeparameter',
            name='production_type',
        ),
    ]
