# Generated by Django 3.0.7 on 2023-07-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0068_remove_skuproductionstagetypeparameter_production_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplanprogress',
            name='soonest_finishing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
