# Generated by Django 3.0.7 on 2023-07-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0069_productionplanprogress_soonest_finishing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplanprogress',
            name='subcontractor_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
