# Generated by Django 3.0.7 on 2023-07-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0070_productionplanprogress_subcontractor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstage',
            name='minimum_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
