# Generated by Django 3.0.7 on 2023-10-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0071_productionstage_minimum_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_in_chinese',
            field=models.CharField(default='', max_length=150),
        ),
    ]
