# Generated by Django 3.0.7 on 2023-10-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0072_product_name_in_chinese'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='transparency',
            field=models.BooleanField(default=False),
        ),
    ]
