# Generated by Django 3.0.7 on 2023-12-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0073_product_transparency'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearestReceivablePurchasedQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('qty', models.IntegerField(default=0)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
