# Generated by Django 3.0.7 on 2024-01-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0074_nearestreceivablepurchasedqty'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('report_id', models.CharField(max_length=10)),
                ('report_start_time', models.DateField()),
                ('report_end_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('order_item_id', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('order_number', models.CharField(max_length=255)),
                ('amount_description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('date_time', models.DateField()),
                ('settlement_id', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=30)),
                ('order_id', models.CharField(max_length=20)),
                ('sku', models.CharField(max_length=20)),
                ('description', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('marketplace', models.CharField(max_length=20)),
                ('fulfillment', models.CharField(max_length=20)),
                ('order_city', models.CharField(max_length=20)),
                ('order_state', models.CharField(max_length=20)),
                ('order_postal', models.CharField(max_length=20)),
                ('product_sales', models.FloatField(default=0)),
                ('shipping_credits', models.FloatField(default=0)),
                ('gift_wrap_credits', models.FloatField(default=0)),
                ('promotional_rebates', models.FloatField(default=0)),
                ('sales_tax_collected', models.FloatField(default=0)),
                ('low_value_goods', models.FloatField(default=0)),
                ('selling_fees', models.FloatField(default=0)),
                ('fba_fees', models.FloatField(default=0)),
                ('other_transaction_fees', models.FloatField(default=0)),
                ('other', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('downloaded_file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesMonitor.DownloadedReport')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('order_number', models.CharField(max_length=7, unique=True)),
                ('shipment_id', models.CharField(max_length=20, unique=True)),
                ('marketplace_name', models.CharField(max_length=20, unique=True)),
                ('transaction_amount', models.FloatField(default=0)),
                ('transaction_type', models.CharField(max_length=20)),
                ('downloaded_file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesMonitor.DownloadedReport')),
            ],
        ),
    ]
