# Generated by Django 3.0.7 on 2024-01-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0075_downloadedreport_order_orderitem_paymenttransactiondetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransactiondetail',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymenttransactiondetail',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='paymenttransactiondetail',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymenttransactiondetail',
            name='settlement_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
