# Generated by Django 3.0.7 on 2024-01-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMonitor', '0076_auto_20240105_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransactiondetail',
            name='settlement_id',
            field=models.CharField(max_length=20),
        ),
    ]
